stages:
  - test
  - report
  - deploy

image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  ALLURE_RESULTS_DIR: allure-results
  ALLURE_REPORT_DIR: public/allure-report
  SWAGGER_COVERAGE_HTML: public/coverage.html
  SWAGGER_COVERAGE_JSON: public/coverage-history.json

cache:
  paths:
    - .cache/pip

before_script:
  - python -m venv venv
  - . venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest --alluredir=$ALLURE_RESULTS_DIR
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIR

generate-report:
  stage: report
  script:
    - mkdir -p public
    - allure-pytest generate $ALLURE_RESULTS_DIR -o $ALLURE_REPORT_DIR
    - python -m swagger_coverage_tool.cli html-report -o $SWAGGER_COVERAGE_HTML
    - python -m swagger_coverage_tool.cli export-history -o $SWAGGER_COVERAGE_JSON
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - test

pages:
  stage: deploy
  script:
    - echo "GitLab Pages deploy stage"
  artifacts:
    paths:
      - public
