generate-report:
  stage: report
  image: ubuntu:22.04
  variables:
    ALLURE_VERSION: "2.27.0"
    ALLURE_HOME: "/opt/allure"
  before_script:
    - apt-get update && apt-get install -y openjdk-17-jdk curl unzip xz-utils
    - curl -L -o allure.tgz "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz"
    - tar -xzf allure.tgz
    - mv allure-${ALLURE_VERSION} $ALLURE_HOME
    - export PATH="$ALLURE_HOME/bin:$PATH"
  script:
    - mkdir -p public
    - allure generate allure-results --clean -o public
    - echo "[Coverage Report](./coverage.html)" > public/coverage-link.md
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
