stages:
  - test
  - report
  - pages

variables:
  ALLURE_VERSION: 2.27.0
  ALLURE_HOME: "$CI_PROJECT_DIR/allure"

test:
  stage: test
  image: python:3.13
  script:
    - apt-get update && apt-get install -y curl openjdk-17-jre
    - pip install -r requirements.txt
    - pytest -m regression --alluredir=allure-results --numprocesses=2
    - swagger-coverage-tool save-report
    - PYTHONPATH=$PYTHONPATH:. python tools/allure/environment.py
  artifacts:
    paths:
      - allure-results/
      - coverage.html
      - coverage-history.json
    expire_in: 1 week

generate-allure-report:
  stage: report
  image: openjdk:17
  script:
    - curl -o allure.tgz -L "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz"
    - tar -xzf allure.tgz && mv allure-${ALLURE_VERSION} $ALLURE_HOME
    - export PATH="$ALLURE_HOME/bin:$PATH"
    - mkdir -p public
    - allure generate allure-results --clean -o public
    - cp coverage.html public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - test

pages:
  stage: pages
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
