stages:
  - test
  - report
  - pages

variables:
  APP_HOST: "http://85.192.34.140:8080"
  PYTHON_VERSION: "3.13"

cache:
  paths:
    - .cache/pip
    - coverage-history.json

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  image: python:$PYTHON_VERSION
  script:
    - pytest -m regression --alluredir=allure-results --numprocesses=2
    - swagger-coverage-tool save-report
  artifacts:
    when: always
    paths:
      - allure-results/
      - coverage-history.json
      - coverage.html
    expire_in: 1 week

generate-allure-report:
  stage: report
  image: python:$PYTHON_VERSION
  dependencies:
    - test
  before_script:
    - apt-get update && apt-get install -y openjdk-11-jre curl unzip
    - curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
    - unzip -o allure.zip -d /opt/
    - export PATH=$PATH:/opt/allure-2.27.0/bin
  script:
    - allure generate allure-results --clean -o public
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: pages
  script:
    - echo "GitLab Pages: публикуем Allure отчет"
  artifacts:
    paths:
      - public
  only:
    - main
