stages:
  - test
  - report
  - pages

variables:
  PYTHON_VERSION: "3.13"

cache:
  key: default
  paths:
    - .venv/
    - coverage-history.json

test:
  stage: test
  image: python:$PYTHON_VERSION
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest -m regression --alluredir=allure-results --numprocesses=2
    - swagger-coverage-tool save-report
  artifacts:
    when: always
    paths:
      - allure-results/
      - coverage.html
      - coverage-history.json
    expire_in: 1 week

generate-report:
  stage: report
  image: python:$PYTHON_VERSION
  dependencies:
    - test
  script:
    - pip install allure-pytest
    - mkdir -p public
    - allure generate allure-results --clean -o public
    - cp coverage.html public/coverage.html
    - cp tools/allure/index.html public/index.html
  artifacts:
    paths:
      - public

pages:
  stage: pages
  script:
    - echo "✅ GitLab Pages успешно опубликованы"
  artifacts:
    paths:
      - public
  only:
    - main
