stages:
  - test
  - report
  - deploy

image: python:3.11

variables:
  ALLURE_VERSION: "2.27.0"
  ALLURE_HOME: "$CI_PROJECT_DIR/allure"
  ALLURE_RESULTS_DIR: "allure-results"
  ALLURE_REPORT_DIR: "public"
  HISTORY_DIR: ".allure-history"

cache:
  paths:
    - .cache/pip

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install allure-pytest

test:
  stage: test
  script:
    - pytest --alluredir=$ALLURE_RESULTS_DIR
    - swagger-coverage-tool save-report
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS_DIR/
      - coverage.html
    expire_in: 1 week

generate-report:
  stage: report
  image: ubuntu:22.04
  dependencies:
    - test
  before_script:
    - apt-get update && apt-get install -y openjdk-17-jdk curl unzip xz-utils
    - curl -L -o allure.tgz "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz"
    - tar -xzf allure.tgz
    - mv "allure-${ALLURE_VERSION}" "$ALLURE_HOME"
    - export PATH="$ALLURE_HOME/bin:$PATH"
  script:
    # Восстанавливаем history из предыдущего пайплайна
    - if [ -d $HISTORY_DIR ]; then cp -r $HISTORY_DIR $ALLURE_RESULTS_DIR/history; fi
    - mkdir -p $ALLURE_REPORT_DIR
    - allure generate $ALLURE_RESULTS_DIR --clean -o $ALLURE_REPORT_DIR
    # Сохраняем history для следующего пайплайна
    - cp -r $ALLURE_REPORT_DIR/history $HISTORY_DIR || echo "No history to save"
    - cp coverage.html $ALLURE_REPORT_DIR/
  artifacts:
    paths:
      - $ALLURE_REPORT_DIR
      - $HISTORY_DIR
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - generate-report
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
